Update codebuild for validation

diff --git a/codebuild/buildspec-validation.yaml b/codebuild/buildspec-validation.yaml
--- a/codebuild/buildspec-validation.yaml
+++ b/codebuild/buildspec-validation.yaml
@@ -25,10 +25,11 @@ phases:
       # Packer does not return non-zero status; we must do that if Packer build failed
       - VALIDATION=true 
       - test -n "$VAL_IMAGE_ID" || VALIDATION=false
+      - echo $VALIDATION
       - >
         if [ $VALIDATION ]; then 
            STATUS='CREATED'
-           echo $VALIDATION
+           echo $STATUS
            sed -i.bak "s/<<AMI-STATUS>>/$STATUS/g" codebuild/ami_builder_event.json;
            sed -i.bak "s/<<AMI-ID>>/$IMAGE_ID/g" codebuild/ami_builder_event.json;
            aws events put-events --entries file://codebuild/ami_builder_event.json;
@@ -38,10 +39,11 @@ phases:
             # tag the image with the ssm parameter version
            aws ec2 create-tags --resources $IMAGE_ID --tags Key=Version,Value=$SSM_PARAM_VERSION;
 
-           [ -x ./codebuild/validate_cleanup.sh ] && ./codebuild/validate_cleanup.sh $VAL_IMAGE_ID || echo 'Not found';
+           [ -x ./codebuild/validate_cleanup.sh ] && ./codebuild/validate_cleanup.sh $VAL_IMAGE_ID || echo 'File validate_cleanup.sh not found';
            aws ssm label-parameter-version --name $SSM_PARAM_NAME --parameter-version $SSM_PARAM_VERSION  --labels AIT-approved;
         else
            STATUS='VALIDATIONFAILED'
+           echo $STATUS
            sed -i.bak "s/<<AMI-STATUS>>/$STATUS/g" codebuild/ami_builder_event.json;
            sed -i.bak "s/<<AMI-ID>>/$IMAGE_ID/g" codebuild/ami_builder_event.json;
            aws events put-events --entries file://codebuild/ami_builder_event.json;
